apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cloudnative-java-service-canary-mobile
  labels:
    app: cloudnative-java-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudnative-java-service
        version: cloudnative-java-service-mobile
    spec:
      containers:
      - image: stmalike/java-service:UPDATE2_0
        imagePullPolicy: IfNotPresent
        name: cloudnative-java-service
        ports:
         - containerPort: 8080
        volumeMounts:
          - name: cloudnative-config
            mountPath: "/config" 
            readOnly: true
      volumes:
      - name: cloudnative-config
        configMap:
          name: cloudnative-config 
          items:
          - key: application.properties
            path: application.properties         
